#### Multiple Linear Regression Practice

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import pickle

In [6]:
df = pd.read_csv("50_Startups.csv")

In [8]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [12]:
df =pd.get_dummies(df, drop_first=True).astype(int)
df.head()

R&D Spend  Administration  ...  State_Florida  State_New York
0     165349          136897  ...              0               1
1     162597          151377  ...              0               0
2     153441          101145  ...              1               0
3     144372          118671  ...              0               1
4     142107           91391  ...              1               0

[5 rows x 6 columns]

In [13]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [16]:
independent =  df[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]

In [18]:
independent.head()

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0     165349          136897           471784              0               1
1     162597          151377           443898              0               0
2     153441          101145           407934              1               0
3     144372          118671           383199              0               1
4     142107           91391           366168              1               0

In [19]:
dependent = df[["Profit"]]
dependent.head()

Profit
0  192261
1  191792
2  191050
3  182901
4  166187

In [20]:
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.2, random_state=42)

In [21]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = regressor.predict(X_test)

In [27]:
y_pred

array([[126362.41393561],
       [ 84608.03582899],
       [ 99676.75421265],
       [ 46357.07247372],
       [128750.2371336 ],
       [ 50912.35215217],
       [109740.30531704],
       [100642.48219079],
       [ 97598.39095783],
       [113096.50866599]])

In [24]:
regressor.coef_[0]

array([ 8.05628626e-01, -6.87898619e-02,  2.98561785e-02,  9.38591972e+02,
        6.96906659e+00])

In [29]:
regressor.intercept_[0]

np.float64(54028.1261921036)

In [33]:
actualscore = r2_score(y_test, y_pred)
actualscore

0.8987226043232428

In [35]:
filename = 'multiple_linear_regression_model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(regressor, file)


In [45]:
inputData = pd.DataFrame({
    'R&D Spend': [153441],
    'Administration': [101145],
    'Marketing Spend': [407934],
    'State_California': [1],
    'State_Florida': [0]
})
input = inputData[['R&D Spend', 'Administration', 'Marketing Spend', 'State_California', 'State_Florida']]


with open(filename, 'rb') as file:
    regressor = pickle.load(file)
regressor.predict(input.values)


/Users/solomon/Documents/Solo_docs/INTO_United_States/Learning_Path/Hope AI /Start Course/Week_2_Python/myevn/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[183804.77995626]])