In [10]:
import numpy as np
import pickle
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score


In [12]:
X, y = make_regression(n_samples=200, n_features=5, noise=20, random_state=42)

# convert to DataFrame for easier handling (optional)
import pandas as pd
df = pd.read_csv("50_Startups.csv")
df = pd.get_dummies(df, columns=['State'], drop_first=True)
X = df.drop('Profit', axis=1)
y = df['Profit']

# X = pd.DataFrame(X, columns=[f'feature_{i}' for i in range(X.shape[1])])
# y = pd.Series(y, name='target')
# df = pd.concat([X, y], axis=1)
#convert to DataFrame
df.head()

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0  165349.20       136897.80        471784.10  192261.83          False   
1  162597.70       151377.59        443898.53  191792.06          False   
2  153441.51       101145.55        407934.54  191050.39           True   
3  144372.41       118671.85        383199.62  182901.99          False   
4  142107.34        91391.77        366168.42  166187.94           True   

   State_New York  
0            True  
1           False  
2           False  
3            True  
4           False

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
print("Step 3: Standardizing Data...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# y_train_scaled = scaler.fit_transform(y_train.values.reshape(-1, 1)).ravel()
# y_test_scaled = scaler.transform(y_test.values.reshape(-1, 1)).ravel()


Step 3: Standardizing Data...


In [ ]:
print("Step 4: Training SVM Regression Model...")
svm_model = SVR(kernel='rbf', C=100, epsilon=0.1)
svm_model.fit(X_train_scaled, y_train)



Step 4: Training SVM Regression Model...


SVR(C=100)

In [16]:
print("Step 5: Saving Model and Scaler to Pickle Files...")
with open('svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)
print("SVM model saved as 'svm_model.pkl'")

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)


Step 5: Saving Model and Scaler to Pickle Files...
SVM model saved as 'svm_model.pkl'


In [17]:
print("Step 7: Loading Model and Scaler from Pickle Files...")
with open('svm_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)
print("SVM model loaded successfully!")

with open('scaler.pkl', 'rb') as f:
    loaded_scaler = pickle.load(f)
print("Scaler loaded successfully!\n")

Step 7: Loading Model and Scaler from Pickle Files...
SVM model loaded successfully!
Scaler loaded successfully!



In [26]:
X_test_sample = X_test[:5]


# Scale using loaded scaler
X_test_sample_scaled = scaler.transform(X_test_sample)
X_test_sample_scaled

## convert X_test_sample to numpy array and reshape
#X_test_sample_array = np.array(X_test_sample).reshape(1, -1)
#X_test_sample_scaled = loaded_scaler.transform(X_test_sample_array)

X_test_sample_array = np.array(X_test_sample)
X_test_sample_array

array([[91992.39, 135495.07, 252664.93, False, False],
       [38558.51, 82982.09, 174999.3, False, False],
       [61994.48, 115641.28, 91131.24, True, False],
       [1000.23, 124153.04, 1903.93, False, True],
       [94657.16, 145077.58, 282574.31, False, True]], dtype=object)

In [27]:
# Make predictions
predictions = loaded_model.predict([[91992.39, 135495.07, 252664.93, False, False]])
print(f"Predictions from loaded model:\n{predictions}\n")

Predictions from loaded model:
[109420.83917597]



In [20]:
# Inverse transform the scaled features back to original scale
X_test_sample_inverse = loaded_scaler.inverse_transform(X_test_sample_scaled)
print(f"Inverse Transformed Features (first 5 samples):\n{X_test_sample_inverse}\n")


Inverse Transformed Features (first 5 samples):
[[9.1992390e+04 1.3549507e+05 2.5266493e+05 0.0000000e+00 0.0000000e+00]
 [3.8558510e+04 8.2982090e+04 1.7499930e+05 0.0000000e+00 0.0000000e+00]
 [6.1994480e+04 1.1564128e+05 9.1131240e+04 1.0000000e+00 0.0000000e+00]
 [1.0002300e+03 1.2415304e+05 1.9039300e+03 0.0000000e+00 1.0000000e+00]
 [9.4657160e+04 1.4507758e+05 2.8257431e+05 0.0000000e+00 1.0000000e+00]]

